### ISSUE TITLE
project x-ray can run on Arm linux ?

### ISSUE THREAD

**Issue by cheungxi** [f4pga/prjxray#1484]
I want to run prjxray on Arm or other architecture linux. But I see,  need vivado 2017.2 ? Only x86 or x86-64?

**Comment by litghost** [comment]
So I think you are confusing two aspects.  If you want to regenerate the prjxray-db database, you need Vivado.  However if you are simply using the database to generate bitstreams, etc, you only require the data from prjxray-db and the python and C++ tools from prjxray.  The CMake file should build the binaries fine on ARM.
