### ISSUE TITLE
Compilation error "make build"

### ISSUE THREAD

**Issue by zipotron** [f4pga/prjxray#2169]
Hi everybody, I am using a recent updated Fedora 38, I was compiling this project in Fedora 36 without issues, but now I get this error:
![compilation_error](https://github.com/f4pga/prjxray/assets/6671137/92b0f280-1a1f-4dc0-8ad9-cf045da97430)

Any suggestion? Thanks!

**Comment by Amjad2004** [comment]
>
> Password reset
>
User ID Amjad2004
Gmail id ***@***.***

**Comment by tmichalak** [comment]
@zipotron the problem you have is related to the fact that the code is using the std::iterator class, which has been marked as deprecated in the C++17 standard.
There is a [PR](#2135) with a fix.

**Comment by pgielda** [comment]
The PR mentioned above (https://github.com/f4pga/prjxray/pull/2135) is merged.

**Comment by zipotron** [comment]
Works! Thanks!
